name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Dremio
        run: |
          cd /tmp && wget https://download.dremio.com/community-server/12.0.0-202012212145230282-d8947fd3/dremio-community-12.0.0-202012212145230282-d8947fd3.tar.gz
          mkdir /opt/dremio && tar xvf /tmp/dremio-community-12.0.0-202012212145230282-d8947fd3.tar.gz -C /opt/dremio --strip-components=1
          export JAVA_EXTRA_OPTS="-Ddebug.addDefaultUser=true"
      - name: Build snowflake JAR
        run: |
          cd $GITHUB_WORKSPACE && mvn install -DskipTests && cp target/*.jar /opt/dremio/jars
          cd /opt/dremio/jars && wget https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.12.16/snowflake-jdbc-3.12.16.jar
      - name: Start Dremio
        run: /opt/dremio/bin/dremio start 
      - name: Wait for Dremio to be available
        run: |
          until curl -Iks http://localhost:9047; do
              echo waiting for dremio
              sleep 1
          done
          cat /opt/dremio/log/server.out
      - name: Run unit tests
        env: 
          SNOWFLAKE_JDBC_URL: ${{ secrets.SNOWFLAKE_JDBC_URL }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: cd $GITHUB_WORKSPACE && mvn test
