name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Dremio
        run: |
          cd /tmp && wget https://download.dremio.com/community-server/17.0.0-202107060524010627-31b5222b/dremio-community-17.0.0-202107060524010627-31b5222b.tar.gz
          mkdir /opt/dremio && tar xvf /tmp/dremio-community-17.0.0-202107060524010627-31b5222b.tar.gz -C /opt/dremio --strip-components=1
      - name: Build snowflake JAR
        run: |
          cd $GITHUB_WORKSPACE && mvn install -DskipTests && cp target/*.jar /opt/dremio/jars
          cd /opt/dremio/jars && wget https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.5/snowflake-jdbc-3.13.5.jar
      - name: Start & wait for Dremio to be available
        run: |
          /opt/dremio/bin/dremio start
          until curl -Iks http://localhost:9047; do
              echo waiting for dremio
              sleep 1
          done
          curl 'http://localhost:9047/apiv2/bootstrap/firstuser' -X PUT -H 'Authorization: _dremionull' -H 'Content-Type: application/json'  --data-binary '{"userName":"dremio","firstName":"dremio","lastName":"dremio","email":"dremio@dremio.com","createdAt":1557027923359,"password":"dremio123"}' --compressed
          cat /opt/dremio/log/server.out
      - name: Run unit tests
        env: 
          SNOWFLAKE_JDBC_URL: ${{ secrets.SNOWFLAKE_JDBC_URL }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: cd $GITHUB_WORKSPACE && mvn test
